### ISSUE TITLE
Procedure for Calibrating Auto Z

### ISSUE THREAD

**Issue by phutruong1801** [Ibot-11/Tap-Automatic-Offset-Calibration#1]
Dear sir,

I appreciate your idea; it is exactly what I need. However, I have some questions and confusion regarding the steps to complete the Auto Z calibration:

   1. Do I need to perform probe_calibrate or Z_endstop_calibrate first?
   2. If I need to calibrate "probe_calibrate," what about "Z_endstop_calibrate"? Should I also use it since the endstop position in the Z configuration is set to 0?
   3. Regarding "TEXTURED_PLATE and SMOOTH_PLATE," how can I calibrate them to achieve optimal results?
   4. Could you create a video demonstrating the complete adjustment and calibration process for the entire procedure?

**Comment by Ibot-11** [comment]
Hey,
here are your answers:
You should do a pobe_calibrate first. It’s just to get a rough z-offset. The finetuning does the macro with the calibration by setting a gcode offset.
You should not change the endstop position since you only use it for calibration.
Yes, set it to 0. It’s only used to calibrate the offset. There is a macro which enables homing via tap. That's the default Z homing method, so no endstop needed here.
When you calibrate your offset with this automatic method Z0 would barely touch your bed. But as we all know there should be some space between bed and nozzle when calibrating the offset manually. So these presets add this certain space.
You need a lower offset for textured plates to push the plastic into it than for smooth surfaces. (Funfact: Bambu also uses a -0.04mm lower offset for textured plates).
 You can change the values when you like some more or less squished first layers. But the default should be a good starting point.
Maybe someday in the future. This calibration is still experimental. There are still some (reliability) issues which are hard to fix.

Please note that this does not work with the default Voron endstop which has a microswitch.

**Comment by phutruong1801** [comment]
Hey there, I've run into a few issues. It seems like the Auto Z function consistently brings the nozzle down a bit too much for the first layer, resulting in a slight squish. I find myself needing to adjust the Z offset to rise around 0.04 or sometimes 0.06 to achieve the perfect Z offset. In this scenario, what specific value should I tweak? The Z offset after running Auto Z typically hovers around 0.08 or 0.09 ( i keep the TEXTURED_PLATE as default)

**Comment by Ibot-11** [comment]
Hey, sorry for the late response.
You can adjust the variable_offset_correction value. Increasing the value will move the nozzle up, decreasing will move the nozzle down.
